---
title: "Github Pages"
date: 2022-01-18


#title: Github Pages 
author: sanduni
email: sanduni.madara@elzian.com
description: > # this means to ignore newlines until "baseurl:"
  Are you ready to make your own website with GitHub Pages. This course will help you create your first website in only a few minutes.
  
theme: minima

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

---
